version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout

     # login to docker hub
     - run: echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin

     # build the application images
     - run: ./build.sh

     # deploy the images
     - run: ./push.sh

workflows:
  version: 2
  build_and_push:
    jobs:
      - build:
          context: docker
